# Generated by Django 3.2.6 on 2021-08-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recloud', '0002_destination_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(default=0),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(default=0, max_length=2000),
        ),
    ]
