# Generated by Django 3.1.4 on 2021-09-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recloud', '0005_cruise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cruise',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
